#made by Giyoung Lee, If you want to help me,contact gy48085@gmail.com
library(Seurat)
epitherial <- c('PLA2G2A', 'CLCA1', 'REG4', 'S100A14', 'ITLN1', 'ELF3', 'PIGR', 'EPCAM', 'REG1B', 'REG1A', 'REG3A','FABP1', 'RBP2', 'SST', 'FABP2', 'SPINK1', 'FABP6', 'AGR2', 'AGR3', 'CLDN3', 'CLDN4', 'DEFA6', 'DEFA5', 'SPINK4', 'ALDOB', 'LCN2', 'KRT8', 'KRT18', 'TSPAN8', 'OLFM4', 'GPX2', 'IFI27', 'PHGR1', 'MT1G', 'CLDN7', 'KRT19', 'FXYD3', 'LGALS4', 'FCGBP', 'TFF3', 'TFF1')
hemo <- c("HBB","HBA1","HBA2")

QC <- function(dir,Sample,type){
	print("Read10X")
	raw.QCdata <- Read10X(data.dir = paste0(dir,"/",Sample))
    print("CreateSeuratObject")
	#QCdata <- CreateSeuratObject(counts = raw.QCdata, project = type, min.cells = 3, min.features = 200)
	QCdata <- CreateSeuratObject(counts = raw.QCdata, project = type)
    #print("percent")
	QCdata[["percent.mt"]] <-  PercentageFeatureSet(QCdata, pattern = "^MT-")
	QCdata[["percent.he"]] <-  PercentageFeatureSet(QCdata, features = hemo)
	QCdata[["percent.ep"]] <-  PercentageFeatureSet(QCdata, features = epitherial)
    print("subset")
	#QCdata <- subset(QCdata, subset = nCount_RNA > 800 & percent.mt < 25 & percent.ep < 1 & percent.he < 10)
	QCdata <- subset(QCdata, subset = nCount_RNA > 1000 & percent.mt < 25 & percent.ep < 1 & percent.he < 10)
	DIM <- dim(QCdata)
	Length <- length(QCdata)
	print(DIM)
	print(Length)
	print(QCdata)
    print("NormalizeData")
	QCdata <- NormalizeData(QCdata, normalization.method = "LogNormalize", scale.factor = 10000)
    print("FindvariableFeatures")
	QCdata <- FindVariableFeatures(QCdata)
    print("ScaleData")
	all.genes <- rownames(QCdata)
	QCdata <- ScaleData(QCdata, features = all.genes)
	print("RunPCA")
	QCdata <- RunPCA(QCdata)
	print("JackStraw")
	QCdata <- JackStraw(QCdata, num.replicate = 100)
    print("ScoreJackStraw")
	QCdata <- ScoreJackStraw(QCdata, reduction = 'pca',dims = 1:20)
    print("FindNeighbors")
	QCdata <- FindNeighbors(QCdata, dims = 1:30)
    print("FindClusters")
	QCdata <- FindClusters(QCdata,   resolution = c(0.2, 0.4, 0.6, 0.8, 1.0))
    print("RunUMAP")
	QCdata <- RunUMAP(QCdata, dims = 1:30)
	saveRDS(QCdata, file = paste0(dir, "output/1.QC/",Sample , "_rds"))
}

